# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_colors.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_colors(object):
    def setupUi(self, colors):
        colors.setObjectName("colors")
        colors.resize(440, 490)
        colors.setMinimumSize(QtCore.QSize(440, 490))
        colors.setMaximumSize(QtCore.QSize(440, 490))
        colors.setStyleSheet("background-color: rgb(255, 229, 211);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(colors)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(17, 440, 411, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_ok.setStyleSheet("\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #100E19;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}")
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.btn_rand_cols = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_rand_cols.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_rand_cols.setStyleSheet("\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #100E19;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}")
        self.btn_rand_cols.setObjectName("btn_rand_cols")
        self.horizontalLayout.addWidget(self.btn_rand_cols)
        self.btn_otmena = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_otmena.setMinimumSize(QtCore.QSize(0, 24))
        self.btn_otmena.setStyleSheet("\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #100E19;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #C0DB50, stop:0.4 #C0DB50, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #C0DB50, stop:1 #C0DB50);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #C0DB50, stop:0.3 #C0DB50, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #d33af1, stop:0.4 #d33af1, stop:0.5 #100E19, stop:1 #100E19);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 #100E19, stop:0.5 #100E19, stop:0.6 #d33af1, stop:1 #d33af1);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d33af1, stop:0.3 #d33af1, stop:0.7 #100E19, stop:1 #100E19);\n"
"    border-width: 2px;\n"
"    border-radius: 1px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}")
        self.btn_otmena.setObjectName("btn_otmena")
        self.horizontalLayout.addWidget(self.btn_otmena)
        self.color_b_1 = QtWidgets.QLabel(colors)
        self.color_b_1.setGeometry(QtCore.QRect(18, 75, 47, 16))
        self.color_b_1.setObjectName("color_b_1")
        self.color_box_9 = QtWidgets.QComboBox(colors)
        self.color_box_9.setGeometry(QtCore.QRect(286, 279, 130, 30))
        self.color_box_9.setStyleSheet("")
        self.color_box_9.setObjectName("color_box_9")
        self.color_box_3 = QtWidgets.QComboBox(colors)
        self.color_box_3.setGeometry(QtCore.QRect(80, 209, 130, 30))
        self.color_box_3.setObjectName("color_box_3")
        self.color_box_4 = QtWidgets.QComboBox(colors)
        self.color_box_4.setGeometry(QtCore.QRect(80, 279, 130, 30))
        self.color_box_4.setObjectName("color_box_4")
        self.color_b_2 = QtWidgets.QLabel(colors)
        self.color_b_2.setGeometry(QtCore.QRect(18, 145, 47, 16))
        self.color_b_2.setObjectName("color_b_2")
        self.color_b_5 = QtWidgets.QLabel(colors)
        self.color_b_5.setGeometry(QtCore.QRect(18, 355, 47, 16))
        self.color_b_5.setObjectName("color_b_5")
        self.color_b_6 = QtWidgets.QLabel(colors)
        self.color_b_6.setGeometry(QtCore.QRect(231, 75, 47, 16))
        self.color_b_6.setObjectName("color_b_6")
        self.color_b_8 = QtWidgets.QLabel(colors)
        self.color_b_8.setGeometry(QtCore.QRect(231, 215, 47, 16))
        self.color_b_8.setObjectName("color_b_8")
        self.color_box_8 = QtWidgets.QComboBox(colors)
        self.color_box_8.setGeometry(QtCore.QRect(286, 209, 130, 30))
        self.color_box_8.setObjectName("color_box_8")
        self.color_box_5 = QtWidgets.QComboBox(colors)
        self.color_box_5.setGeometry(QtCore.QRect(80, 349, 130, 30))
        self.color_box_5.setObjectName("color_box_5")
        self.color_box_7 = QtWidgets.QComboBox(colors)
        self.color_box_7.setGeometry(QtCore.QRect(286, 139, 130, 30))
        self.color_box_7.setObjectName("color_box_7")
        self.color_box_6 = QtWidgets.QComboBox(colors)
        self.color_box_6.setGeometry(QtCore.QRect(286, 69, 130, 30))
        self.color_box_6.setObjectName("color_box_6")
        self.color_b_10 = QtWidgets.QLabel(colors)
        self.color_b_10.setGeometry(QtCore.QRect(231, 355, 47, 16))
        self.color_b_10.setObjectName("color_b_10")
        self.color_b_7 = QtWidgets.QLabel(colors)
        self.color_b_7.setGeometry(QtCore.QRect(231, 145, 47, 16))
        self.color_b_7.setObjectName("color_b_7")
        self.color_b_4 = QtWidgets.QLabel(colors)
        self.color_b_4.setGeometry(QtCore.QRect(18, 285, 47, 16))
        self.color_b_4.setObjectName("color_b_4")
        self.color_b_9 = QtWidgets.QLabel(colors)
        self.color_b_9.setGeometry(QtCore.QRect(231, 285, 47, 16))
        self.color_b_9.setObjectName("color_b_9")
        self.color_box_10 = QtWidgets.QComboBox(colors)
        self.color_box_10.setGeometry(QtCore.QRect(286, 349, 130, 30))
        self.color_box_10.setObjectName("color_box_10")
        self.color_b_3 = QtWidgets.QLabel(colors)
        self.color_b_3.setGeometry(QtCore.QRect(18, 215, 47, 16))
        self.color_b_3.setObjectName("color_b_3")
        self.color_box_2 = QtWidgets.QComboBox(colors)
        self.color_box_2.setGeometry(QtCore.QRect(80, 139, 130, 30))
        self.color_box_2.setObjectName("color_box_2")
        self.color_box_1 = QtWidgets.QComboBox(colors)
        self.color_box_1.setGeometry(QtCore.QRect(80, 69, 130, 30))
        self.color_box_1.setStyleSheet("")
        self.color_box_1.setObjectName("color_box_1")

        self.retranslateUi(colors)
        QtCore.QMetaObject.connectSlotsByName(colors)

    def retranslateUi(self, colors):
        _translate = QtCore.QCoreApplication.translate
        colors.setWindowTitle(_translate("colors", "Настройки цвета"))
        self.btn_ok.setText(_translate("colors", "Ок"))
        self.btn_rand_cols.setText(_translate("colors", "Случайные цвета"))
        self.btn_otmena.setText(_translate("colors", "Отмена"))
        self.color_b_1.setText(_translate("colors", "Bucket 1"))
        self.color_b_2.setText(_translate("colors", "Bucket 2"))
        self.color_b_5.setText(_translate("colors", "Bucket 5"))
        self.color_b_6.setText(_translate("colors", "Bucket 6"))
        self.color_b_8.setText(_translate("colors", "Bucket 8"))
        self.color_b_10.setText(_translate("colors", "Bucket 10"))
        self.color_b_7.setText(_translate("colors", "Bucket 7"))
        self.color_b_4.setText(_translate("colors", "Bucket 4"))
        self.color_b_9.setText(_translate("colors", "Bucket 9"))
        self.color_b_3.setText(_translate("colors", "Bucket 3"))
